# Generated by Django 4.0.2 on 2022-03-27 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_monthly_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='passes',
            field=models.IntegerField(default=1),
        ),
    ]
