# Generated by Django 4.0.2 on 2022-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_time', models.CharField(max_length=64)),
                ('end_time', models.CharField(max_length=64)),
                ('days_of_week', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
