# Generated by Django 4.0.2 on 2022-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_membership_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='membership',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
