# Generated by Django 4.0.2 on 2022-03-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_membership_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
