# Generated by Django 4.0.2 on 2022-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_membership_purchase_date_membership_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('no pass', 'No Pass'), ('single visit', 'Single Visit'), ('punch pass', 'Punch Pass'), ('monthly membership', 'Monthly Membership')], default='no pass', max_length=64),
        ),
    ]
