# Generated by Django 4.0.2 on 2022-03-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
    ]
