# Generated by Django 4.0.2 on 2022-03-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_membership_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
