# Generated by Django 4.0.2 on 2022-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_signup_class_user_signup_selected_class_signup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('no pass', 'No Pass'), ('single visit', 'Single Visit'), ('ten visit', 'Ten Visit'), ('monthly membership', 'Monthly Membership')], default='no pass', max_length=64),
        ),
    ]
