# Generated by Django 4.0.2 on 2022-03-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_scheduledclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='days_of_week',
        ),
    ]
