# Generated by Django 4.0.2 on 2022-04-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_remove_class_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='purchased_type',
            field=models.CharField(choices=[('class_pass', 'Class Pass'), ('monthly membership', 'Monthly Membership')], default='class_pass', max_length=64),
        ),
    ]
